name: "merge_to_main"

on:
  pull_request:
    branches:
      - main

jobs:
  pylint_run:
    name: "Run Pylint"
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.6.0
    - name: Install Pylint
      run: pip3 install pylint
    - name: Install Requirements
      run: pip3 install -r requirements.txt
    - name: Run Pylint on all db_component python files
      run: pylint --fail-under=8 db_components/*.py
    - name: Run Pylint on all etl_pipeline python files
      run: pylint --fail-under=8 etl_pipeline/*.py


  pytest_run:
    name: "Run Pytest on the code"
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.6.0
    - name: Install Pytest
      run: pip3 install pytest
    - name: Install Requirements
      run: pip3 install -r requirements.txt
    - name: Run Pytest on all etl_pipeline files
      run: pytest etl_pipeline/tests/test_*.py
    - name: Run Pytest on all db_components files
      run: pytest db_components/test_*.py
